// "use client"
import "./globals.css";
import type { Session } from 'next-auth';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/AuthProvider";
// import { signIn, signOut, useSession, getProviders } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: React.ReactNode;
  session: Session | null;
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,session }:  RootLayoutProps) {
  // const session = useSession();

  return (
    <html lang="en">
      <body>
        <AuthProvider session={session}>
          <Navbar />
          {/* <Navbar authenticated={false} name='null' image='null'/> */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
